# lnmp
version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    ports:
    - "3306:3306"
    volumes:
    - ./mysql/data:/var/lib/mysql
    - ./mysql/conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    - ./mysql/conf/my.cnf:/etc/mysql/my.cnf
    - ./mysql/logs:/var/log/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=root
    command: --default-authentication-plugin=mysql_native_password #支持远程访问
    networks:
    - lnmp

  redis:
    image: redis:4
    container_name: redis
    hostname: redis
    volumes:
    - ./redis/data:/data
    - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
    - "6379:6379"
    networks:
    - lnmp

  php:
    build: ./phpfpm
    container_name: php
    hostname: php
    ports:
      - "9000:9000"
    links:
      - mysql:mysql
      - redis:redis
    volumes:
      - /Users/chenyinshan/code:/www
      - ./phpfpm/conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ./phpfpm/conf/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./phpfpm/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./composer:/data
    networks:
      - lnmp

  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    ports:
    - "80:80"
    volumes:
    - /Users/chenyinshan/code:/www
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    links:
    - php:PHP-FPM
    networks:
    - lnmp

networks:
  lnmp:
    driver: bridge

  
